name: Publish Coverage to GitHub Pages

on:
  push:
    branches:
      - main
      - trunk

jobs:
  publish-coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to push to gh-pages branch

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for gh-pages push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests and generate coverage
        run: |
          pytest --cov=backend --cov=frontend --cov=scripts --cov-report=html:coverage_html tests/
          ls -la coverage_html

      - name: Check contents of coverage_html
        run: |
          if [ -d coverage_html ]; then
            echo "✅ coverage_html folder found. Contents:"
            ls -l coverage_html
          else
            echo "❌ coverage_html folder is missing!"
            exit 1
          fi
          [ -f coverage_html/index.html ] && echo "✅ Found coverage_html/index.html" || (echo "❌ No index.htmln in coverage_html folder" && exit 1)
        
      - name: Deploy coverage to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage_html
          publish_branch: gh-pages
          force_orphan: true
          enable_jekyll: false
          commit_message: "Publish coverage report from ${{ github.sha }}"
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
